//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tm2TestAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nouchi
    {
        public int MapDataID { get; set; }
        public string Chiban { get; set; }
        public string Sakuki { get; set; }
        public string SakumotsuMei { get; set; }
        public string Chimoku { get; set; }
        public Nullable<int> Area { get; set; }
    }
}
